### ISSUE TITLE
parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'r'

### ISSUE THREAD

**Issue by perdakovich** [ProgrammerIn-wonderland/freetok#2]
Installed from AUR `freetok-cpp-git`

```

Something went wrong :(
details are provided below

message: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'r'
exception id: 101
byte position of error: 1
```

**Comment by ProgrammerIn-wonderland** [comment]
Oh I actually forgot I ever made this, not sure if I can get it to work again but the way it worked was very primitive, each tiktok page had some json data between two markers but it constantly changes. I'd recommend using yt-dlp on the official archlinux mirrors as a replacement, it works with tiktok. Use `yt-dlp -g https://tiktok.com/link` for the same effect as this project

Apologies I'll delist from the aur

**Comment by perdakovich** [comment]
Just happened to find this on AUR and I was curious to try it.
Thanks for a great feedback!  

Sadly, `yt-dlp` doesn't work for me, says "Video not available, status code 10204" every time
